version: "3.8"

networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.255.0/24
      driver: default

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: arch
      POSTGRES_USER: arch
      POSTGRES_DB: arch
    restart: always
  nats-streaming-1:
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - nats-streaming
      - "--clustered"
      - "--cluster_bootstrap"
      - "--cluster_log_path"
      - /data/log
      - "--cluster_node_id"
      - nats-streaming-1
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - /data/msg
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--store"
      - file
      - "--stan_debug"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    image: "nats-streaming:0.17.0"
    networks:
      - main
    ports:
      - "14222:4222"
      - "18222:8222"
    volumes:
      - "./nats/nats-streaming-1:/data"
  nats-streaming-2:
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - nats-streaming
      - "--clustered"
      - "--cluster_log_path"
      - /data/log
      - "--cluster_node_id"
      - nats-streaming-2
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - /data/msg
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--store"
      - file
      - "--stan_debug"
      - "--routes"
      - "nats://nats-streaming-1:5222"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    image: "nats-streaming:0.17.0"
    networks:
      - main
    ports:
      - "24222:4222"
      - "28222:8222"
    volumes:
      - "./nats/nats-streaming-2:/data"
  nats-streaming-3:
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - nats-streaming
      - "--clustered"
      - "--cluster_log_path"
      - /data/log
      - "--cluster_node_id"
      - nats-streaming-3
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - /data/msg
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--store"
      - file
      - "--stan_debug"
      - "--routes"
      - "nats://nats-streaming-1:6222"
      - "--hb_interval"
      - 2s
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - 5s
    image: "nats-streaming:0.17.0"
    networks:
      - main
    ports:
      - "34222:4222"
      - "38222:8222"
    volumes:
      - "./nats/nats-streaming-3:/data"